name: CI
on:
  push:
    branches: [ master ]

jobs:
  get_latest_stats:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # build meta.json file for further use within the webclient
      # magic happends in ci/build.sh
    - name: create_json_stats_file
      run: |
        chmod 700 ci/build.sh
        cd ci
        ./build.sh
        
