name: CI
on:
  push:
    branches: [ master ]

jobs:
  get_latest_stats:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 
        persist-credentials: false
      # build meta.json file for further use within the webclient
      # magic happends in ci/build.sh
    - name: create_json_stats_file
      env:
        GITHUB_TOKEN:  ${{secrets.PUSH_KEY}}
      run: |
        chmod 700 ci/build.sh
        cd ci
        ./build.sh
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: "stats"
        github_token: ${{ secrets.PUSH_KEY }}
